[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "python39", "python39Packages.pip"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-interaction",
    "cd python_service && python -m pip install -r requirements.txt --user"
]

[start]
cmd = "bash start-production.sh"
