[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "python3"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-interaction",
    "cd python_service && python3 -m ensurepip --default-pip",
    "cd python_service && python3 -m pip install --upgrade pip",
    "cd python_service && python3 -m pip install -r requirements.txt"
]

[start]
cmd = "bash start-production.sh"
